### ISSUE TITLE
How to use multichain target?

### ISSUE THREAD

**Issue by amin-sagar** [Kuhlman-Lab/evopro#19]
Hello.
I am trying to work with a multichain target.
I tried generating the msa of the target complex (2 chains) and supply it as custom msa and just run the AF2 step (no GA). 
```
--input_dir input
--output_dir AFmult/predictions
--params_dir /home/amin/softwares/Protein-Design/params-2022-12-06/
--compress_output
--use_ptm
--msa_mode single_sequence
--custom_msa_path /home/amin/Work/Project_42/msas_complex
--max_recycle 4
--save_timing
--num_models 5
--num_seeds 5
```
But this doesn't seem to work as the target is unfolded. If I use a polyglycine linker to link the two chains and use the msa of the joint construct, it works well, but I would like to use multimer to model the complex as it might be more accurate.
I see there is an example in the dev branch.
[https://github.com/Kuhlman-Lab/evopro/blob/dev/evopro/examples/example/af2_flags.txt](url)
From the example, it seems like I should provide templates.
Could you please tell me what format the msa should be in and how to specify the multi chain templates?
I would be  really grateful for any suggestions.
Best,
Amin.

**Comment by amritan1707** [comment]
Hi,

Yes, sometimes just the MSA is not enough information for AF2 to fold the target correctly, so you can use a template to supplement information here. The MSA should be in .a3m file format and it should be within the directory which you specify in custom_msa_path. 
To provide templates, you can use the custom template feature in our version of AF2. To use this, add flags in your af2.flags as below:
```
--use_templates
--custom_template_path templates
```

Then, create a directory called **templates** within your run directory and add PDB files into it with your correctly predicted complex. Since AF2 treats each subunit individually during template parsing, you can have a PDB file for each subunit or have them all within the same PDB. Finally, since we have modified the original AF2 code to allow for custom templates, you will have to make sure each .pdb file within that folder has a name consisting of 4 letters and numbers, essentially mimicking a file from the PDB database with a PDB code (although the file name does not actually have to be a real PDB code). Some examples could be “temp.pdb”, “1uzg.pdb”, “PPPP.pdb”, etc.

Thanks,
Amrita

**Comment by amin-sagar** [comment]
Thanks @amritan1707 , this is very helpful.

I have understood a part of the problem. I thought I was doing something wrong because when I was just predicting the structure of the protein using colabfold (local), I was getting well folded models which agreed very nicely with the crystal structure. Then, I gave the same msa to evopro/your alphafold and the protein was unfolded. 

I then tried to let your version of alphafold generate msa and model the target and then supplied that msa as custom msa for modelling the target+peptide in single sequence mode. Now, everything works perfectly. So, it seems I can't use the colabfold generated msa with your version of alphafold, which is not a problem but I didn't realize that.

What I am trying to do is as follows.
Model ~ 1000 peptides with the multi-chain target with your version of alphafold > Find the best 10 candidates > refine them with EVOPRO.

This is not really an EVOPRO question and if you like, I can raise an issue in the alphafold repo, but I would really appreciate your help.
Are there some example scripts to run such batch modelling problem on multiple GPUs using your version of AlphaFold? If I just run your version of AlphaFold using 
```
python ./EVOPRO/alphafold/run/run_af2.py @af2_flags.txt
```
It uses a single GPU.
I would be really grateful for your help.

**Comment by amritan1707** [comment]
Hi,
I have just added our script that uses the runtime optimized multi-GPU AF2 from EvoPro, to just run AF2. Please see evopro/run/run_af2_dist.py for flag options and details!

**Comment by amritan1707** [comment]
Please use --design_run flag in your af2.flags file, that should fix the problem. It tells the run_af2 function to return the results rather than write out the results and return a NoneType object.

**Comment by amin-sagar** [comment]
Thanks a lot @amritan1707 . This works. One last question, I promise.
Where can I find the generated files while the modelling is running?
It seems the output folder appears only after the run is completed, so the files must be getting saved in a temporary folder somewhere.
I am concerned that if the job runs out of time or crashes or I fill up the disk space, I won't know where to find the files.

**Comment by amritan1707** [comment]
Yes, you can only get the files after the whole run is completed. The files are only written out after all the sequences have been processed through - since the information has to come back from the GPU to the CPU for writing to disk, this cannot be done until the end.
